LANGUAGES = {
    "en": {
        "language_name": "English",
        "app_name": "UzHealthAI",
        "ai_symptom_checker": "AI Symptom Checker",
        "find_clinics": "Find Clinics",
        "health_tips": "Health Tips",
        "describe_symptoms": "Describe your symptoms...",
        "submit": "Submit",
        "diagnosis": "Your diagnosis will appear here.",
        "back_to_main_menu": "Back to Main Menu",
        "find_nearby_clinics": "Click the button below to find nearby clinics.",
        "contact_info": "Contact: info@uzhealthai.com | Support: support@uzhealthai.com",
    },
    "uz": {
        "language_name": "O'zbekcha",
        "app_name": "UzHealthAI",
        "ai_symptom_checker": "AI Simptomlar Tekshiruvi",
        "find_clinics": "Klinikalarni Topish",
        "health_tips": "Sog'liq Maslahatlari",
        "describe_symptoms": "Simptomlaringizni tasvirlang...",
        "submit": "Yuborish",
        "diagnosis": "Tashxisingiz shu yerda ko'rinadi.",
        "back_to_main_menu": "Asosiy Menyuga Qaytish",
        "find_nearby_clinics": "Yaqin atrofdagi klinikalarni topish uchun quyidagi tugmani bosing.",
        "contact_info": "Aloqa: info@uzhealthai.com | Yordam: support@uzhealthai.com",
    },
    "ru": {
        "language_name": "Русский",
        "app_name": "UzHealthAI",
        "ai_symptom_checker": "AI Проверка Симптомов",
        "find_clinics": "Найти Клиники",
        "health_tips": "Советы по Здоровью",
        "describe_symptoms": "Опишите ваши симптомы...",
        "submit": "Отправить",
        "diagnosis": "Ваш диагноз появится здесь.",
        "back_to_main_menu": "Вернуться в Главное Меню",
        "find_nearby_clinics": "Нажмите кнопку ниже, чтобы найти ближайшие клиники.",
        "contact_info": "Контакт: info@uzhealthai.com | Поддержка: support@uzhealthai.com",
    }
}